# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'OLCOrm' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'FMDB'
  
  # Pods for OLCOrm
  pod "OLCOrm", :path => "../"

end
