target 'OLCOrm', :exclusive => true do
  pod "OLCOrm", :path => "../"
  pod 'FMDB'
end

target 'Tests', :exclusive => true do
  pod "OLCOrm", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
